import Head from 'next/head'
import Image from 'next/image'
import NavList from "../components/nav_list";

export default function Home() {
  return (
    <div>
      <Head>
        <title>弯道超车</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-screen-2xl mx-auto">
        <h1 className='text-4xl md:text-7xl pt-4 font-bold text-center py-10'>动效列表</h1>
        <NavList />
      </main>
    </div>
  )
}
